### ISSUE TITLE
Font imported using @fontface is not working after doing build with vulcanize

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [Polymer/vulcanize#159]
I am using - **NotoSansGurmukhi-Regular.ttf** in a Polymer App
```css
    @font-face {
      font-family: 'Dejaweb';
      src: url('fonts/NotoSansGurmukhi-Regular.ttf');
    }
```
After build - using vulcanized my Font gets converted into something like this.
**¨à¨®à¨¹à¨²à¨¾à©©à¥¥à¨®à¨¨à¨®à©à¨–à¨ªà©œà¨¹à¨¿à¨ªà©°à¨¡à¨¿à**

Though it is loading the font correctly. 

Without build it is working fine. Please let me know whats the issue and how to resolve it.
