### ISSUE TITLE
@apply in external css gets truncated in vulcanized output

### ISSUE THREAD

**Issue by gazal-k** [Polymer/vulcanize#229]
[@apply](https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins) Custom CSS Mixins declared in external CSS file works fine when serving before vulcanizing.
But vulcanized output seems to truncate it.

### Reproduced with:
gulp-vulcanize#6.0.1

### Example:

External CSS; my-element.css
```css
:host {
  display: block;
}
.rows {
  @apply(--layout-vertical);
  @apply(--layout-flex);
}
.cols {
  @apply(--layout-horizontal);
  @apply(--layout-flex);
}
```
Element my-element.html
```html
<dom-module id="my-element">
  <link rel="import" type="css" href="my-element.css">
  <template>
   My Custom Element!
  </template>
  <script>
  Polymer({
    is : 'my-element'
  });
  </script>
</dom-module>
```

Vulcanized output:
```html
<dom-module id="my-element">
  <style>
:host {
  display: block;
}
</style>
  <template>
   My Custom Element!
  </template>
  <script>
  Polymer({
    is : 'my-element'
  });
  </script>
</dom-module>
```

### Workaround:
 - Use inline CSS if you need to use Custom CSS Mixins
